#include <QWidget>
#include <QPushButton>
#include <QLineEdit>
#include <QMainWindow>
#include <QStackedWidget>
#include <QGridLayout>
#include <QDebug>
#include <QPainter>
#include <QPaintEvent>
#include <QSpacerItem>
#include <QIntValidator>
#include <QTimer>
#include <QLabel>
#include <QFile>
